r		ifndef	__regskelinc
__regskelinc	equ	1
                save
                listing off   ; no listing over this file

;****************************************************************************
;*                                                                          *
;*   AS 1.42 - File REGSKEL.INC                                             *
;*                                                                          *
;*   Contains Bit & Register Definitions for ATSkel                         *
;*                                                                          *
;****************************************************************************


		restore			; re-enable listing

		endif			; __regskelinc
