# -------------------------------------------------------------------------
# choose your compiler (must be ANSI-compliant!) and linker command, plus
# any additionally needed flags

OBJDIR =
CC = bcc
CFLAGS =-WX -ml -Oe -k- -Z -d -dc
HOST_OBJEXTENSION = .obj
LD = bcc -WX
LDFLAGS =
HOST_EXEXTENSION = .exe 

# no cross build

TARG_OBJDIR = $(OBJDIR)
TARG_CC = $(CC)
TARG_CFLAGS = $(CFLAGS)
TARG_OBJEXTENSION = $(HOST_OBJEXTENSION)
TARG_LD = $(LD)
TARG_LDFLAGS = $(LDFLAGS)
TARG_EXEXTENSION = $(HOST_EXEXTENSION)

# -------------------------------------------------------------------------
# directories where binaries, includes, and manpages should go during
# installation

BINDIR = c:\as\bin
INCDIR = c:\as\include
MANDIR = c:\as\man
LIBDIR = c:\as\lib
DOCDIR = c:\as\doc

# -------------------------------------------------------------------------
# character encoding to use (choose one of them)

# CHARSET = CHARSET_ISO8859_1
# CHARSET = CHARSET_ASCII7
CHARSET = CHARSET_IBM437
# CHARSET = CHARSET_IBM850
