# -------------------------------------------------------------------------
# choose your compiler (must be ANSI-compliant!) and linker command, plus
# any additionally needed flags

OBJDIR =
CC = vicc
OBJOPT = "/Fo"
CFLAGS =
HOST_OBJEXTENSION = .obj
LD = vlink
OUTOPT = "/O:"
LDFLAGS = /PM:VIO
HOST_EXEXTENSION = .exe

# no cross build

TARG_OBJDIR = $(OBJDIR)
TARG_CC = $(CC)
TARG_CFLAGS = $(CFLAGS)
TARG_OBJEXTENSION = $(HOST_OBJEXTENSION)
TARG_LD = $(LD)
TARG_LDFLAGS = $(LDFLAGS)
TARG_EXEXTENSION = $(HOST_EXEXTENSION)

# -------------------------------------------------------------------------
# directories where binaries, includes, and manpages should go during
# installation

BINDIR = .
INCDIR = m:/as/include
MANDIR = .
