# -------------------------------------------------------------------------
# choose your compiler (must be ANSI-compliant!) and linker command, plus
# any additionally needed flags

CC = bcc
LD = bcc -WX
CFLAGS =-WX -ml -Oe -k- -Z -d

# -------------------------------------------------------------------------
# directories where binaries, includes, and manpages should go during
# installation

BINDIR = c:\as\bin
INCDIR = c:\as\include
MANDIR = c:\as\man
LIBDIR = c:\as\lib
DOCDIR = c:\as\doc

# -------------------------------------------------------------------------
# character encoding to use (choose one of them)

# CHARSET = CHARSET_ISO8859_1
# CHARSET = CHARSET_ASCII7
CHARSET = CHARSET_IBM437
# CHARSET = CHARSET_IBM850

# -------------------------------------------------------------------------
# DOS special...

EXEXTENSION=.exe
