# -------------------------------------------------------------------------
# choose your compiler (must be ANSI-compliant!) and linker command, plus
# any additionally needed flags

# NOTE: The egcs version shipped with Cygwin B20 seems to have trouble with
#       optimization level 3, don't use it :-/

OBJDIR =
CC = gcc
CFLAGS = -O2 -mcpu=i486 -Wall -Wno-parentheses -Wno-sign-compare
HOST_OBJEXTENSION = .o
LD = gcc
LDFLAGS =
HOST_EXEXTENSION = .exe

# no cross build

TARG_OBJDIR = $(OBJDIR)
TARG_CC = $(CC)
TARG_CFLAGS = $(CFLAGS)
TARG_OBJEXTENSION = $(HOST_OBJEXTENSION)
TARG_LD = $(LD)
TARG_LDFLAGS = $(LDFLAGS)
TARG_EXEXTENSION = $(HOST_EXEXTENSION)

BINDIR = /usr/local/bin
INCDIR = /usr/local/include/asl
MANDIR = /usr/local/man
LIBDIR = /usr/local/lib/asl
DOCDIR = /usr/local/doc/asl
