# -------------------------------------------------------------------------
# choose your compiler (must be ANSI-compliant!) and linker command, plus
# any additionally needed flags

# NOTE: The egcs version shipped with Cygwin B20 seems to have trouble with
#       optimization level 3, don't use it :-/

CC = gcc
LD = gcc
CFLAGS = -O2 -Wall -Wno-parentheses -Wno-sign-compare
LDFLAGS =

# -------------------------------------------------------------------------
# directories where binaries, includes, and manpages should go during
# installation

EXEXTENSION=.exe

BINDIR = /usr/local/bin
INCDIR = /usr/local/include/asl
MANDIR = /usr/local/man
LIBDIR = /usr/local/lib/asl
DOCDIR = /usr/local/doc/asl

# -------------------------------------------------------------------------
# character encoding to use (choose one of them)

# CHARSET = CHARSET_ASCII7
# CHARSET = CHARSET_IBM437
CHARSET = CHARSET_IBM850
# CHARSET = CHARSET_ISO8859_1
