		ifndef	__templateinc	; avoid multiple inclusion
__templateinc	equ	1

		save
		listing	off		; no listing over this file

;****************************************************************************
;*                                                                          *
;*   AS 1.42 - File TEMPLATE.INC                                            *
;*                                                                          *
;*   contains SFR and Bit Definitions for                        *
;*                                                                          *
;****************************************************************************

		restore
		endif			; __templateinc
