; ****************************************************************************
; Definition der Modulnamen
; Format:
;      defModul <Modulname>, <Netzwerkadressse>
;
; Dem <Modulname> wird eine eindeutige Zahl zugeordnet.
;
       defModul  Rob,        uC_Rob
       defModul  Frs,        uC_Frs
       defModul  TeachRob,   uC_Teach_Rob
       defModul  TeachFrs,   uC_Teach_Frs
       defModul  TeachKey,   uC_Teach_Key
       defModul  MemRob,     uC_Teach_Rob
       defModul  MemFrs,     uC_Teach_Frs
       defModul  PC_SIO,     uC_PC_SIO

;
; ****************************************************************************
