# -------------------------------------------------------------------------
# choose your compiler (must be ANSI-compliant!) and linker command, plus
# any additionally needed flags

OBJDIR =
CC = gcc
CFLAGS = -g -O3 -fomit-frame-pointer -Wall -Wextra -Werror -Wstrict-prototypes
#CFLAGS = -g -O3 -fomit-frame-pointer -Wall -Wextra -Werror -Wstrict-prototypes -ansi -std=c89 -pedantic
HOST_OBJEXTENSION = .o
LD = $(CC)
LDFLAGS =
HOST_EXEXTENSION =

TARG_OBJDIR = i686-w32/
TARG_CC = i686-w64-mingw32-gcc
TARG_CFLAGS = $(CFLAGS)
TARG_OBJEXTENSION = .o
TARG_LD = $(TARG_CC)
TARG_LDFLAGS =
TARG_EXEXTENSION = .exe
TARG_RUNCMD = wine
TEX2DOC_FLAGS=-codepage 1252

# -------------------------------------------------------------------------
# directories where binaries, includes, and manpages should go during
# installation

BINDIR = /usr/local/bin
INCDIR = /usr/local/include/asl
MANDIR = /usr/local/man
LIBDIR = /usr/local/lib/asl
DOCDIR = /usr/local/doc/asl
