#!/bin/bash

echo executing self tests...
echo "=================================================================" > ../testlog
echo "Summaric results:" >> ../testlog
SUMPASS="0"
SUMFAIL="0"
if [ "$1" = "" ]; then
    SUBDIRS="t_*"
else
    SUBDIRS="$1"
fi
if [ "$V" != "1" ]; then
    QUIET="-q"
fi

for t in $SUBDIRS; do
    if test -f "$t/$t.asm"; then
        if test -f "$t/$t.ori"; then
            if cd "$t" ; then
                if test "$V" = "1"; then
                    cat "$t.doc"
                fi
                # valgrind --leak-check=yes  ...
                IFS=$' \t\r\n' read -ra args < asflags
                ${RUNCMD} "../../${OBJDIR}asl${EXEXTENSION}" "${args[@]}" $QUIET -Werror -i ../../include "$t.asm" | tee "$t.log"
                ${RUNCMD} "../../${OBJDIR}p2bin${EXEXTENSION}" $QUIET -k -l 0 -r 0x-0x "$t"
                if test "$V" = "1"; then
                    echo +---------------------------------------------------------------+
                fi
                if cmp -b "$t.ori" "$t.bin"; then
                    if test "$V" = "1"; then
                        echo "Test $t succeeded!"
                    fi
                    echo "$t : OK" >> ../../testlog
                    SUMPASS=$(( SUMPASS + 1 ))
                else
                    echo "Test $t failed!"
                    SUMFAIL=$(( SUMFAIL + 1 ))
                    { echo "$t : failed"; echo "$t : expected"; od -tx1 -v -An "$t.ori"; echo "$t : obtained"; od -tx1 -v -An "$t.bin"; } >> ../../testlog
                fi
                grep assembly "$t.log" >> ../../testlog
                grep Assemblierzeit "$t.log" >> ../../testlog
                if test "$V" = "1"; then
                    echo +---------------------------------------------------------------+
                fi
                rm -f "$t.bin" "$t.log" "$t.h"
                cd ..
            else
                echo "$t : no such test" >> ../testlog
                SUMFAIL=$(( SUMFAIL + 1 ))
            fi
        fi
    fi
done
{ echo "successes: $SUMPASS"; echo "failures : $SUMFAIL"; } >> ../testlog
if [ "$V" = "1" ] || [ "$SUMFAIL" != "0" ]; then
    cat ../testlog
else
    echo "successes: $SUMPASS"
    echo "failures : $SUMFAIL"
fi
if test "$SUMFAIL" = "0"; then
    exit 0
else
    exit 1
fi
