name: ci-emscripten

on:
  push:
    paths:
      - '**'
      - '!*.bat'
      - '!*.cmd'
      - '!*.sh'
      - '!doc_COM/*'
      - '!doc_DE/*'
      - '!doc_EN/*'
      - '!include/**'
      - '!man/*'
      - '!COPYING'
      - '!INSTALL'
      - '!README*'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-emscripten.yml'
  pull_request:
    paths:
      - '**'
      - '!*.bat'
      - '!*.cmd'
      - '!*.sh'
      - '!doc_COM/*'
      - '!doc_DE/*'
      - '!doc_EN/*'
      - '!include/**'
      - '!man/*'
      - '!COPYING'
      - '!INSTALL'
      - '!README*'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-emscripten.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  ci-emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-fast update
          sudo apt-fast install -y cmake ninja-build
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11'
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
      - name: Configure Host
        run: |
          cmake -S . -B build-host
      - name: Build Host
        run: |
          cmake --build build-host -j --target rescomp
      - name: Configure Target
        run: |
          emcmake cmake -S . -B build -DIMPORT_EXECUTABLES=build-host/ImportExecutables.cmake -DCMAKE_BUILD_TYPE=DEBUG
      - name: Build Target
        run: |
          cmake --build build -j
      - name: Test
        env:
          VERBOSE: 1
        run: |
          ctest --build-run-dir build --test-dir build -j --rerun-failed --output-on-failure
