name: ci-macos

on:
  push:
    paths:
      - '**'
      - '!*.bat'
      - '!*.cmd'
      - '!*.sh'
      - '!doc_COM/*'
      - '!doc_DE/*'
      - '!doc_EN/*'
      - '!include/**'
      - '!man/*'
      - '!COPYING'
      - '!INSTALL'
      - '!README*'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'
  pull_request:
    paths:
      - '**'
      - '!*.bat'
      - '!*.cmd'
      - '!*.sh'
      - '!doc_COM/*'
      - '!doc_DE/*'
      - '!doc_EN/*'
      - '!include/**'
      - '!man/*'
      - '!COPYING'
      - '!INSTALL'
      - '!README*'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  ci-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]  # macos-13 is the last x86_64 version.
        generator: [Ninja]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew upgrade || true
          brew install cmake ninja
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11'
      - name: Checkout code
        uses: actions/checkout@master
      - name: Configure
        run: |
          cmake -S . -B build -G ${{ matrix.generator }} -DCMAKE_BUILD_TYPE=DEBUG
      - name: Build
        run: |
          cmake --build build -j
      - name: Test
        env:
          VERBOSE: 1
        run: |
          ctest --build-run-dir build --test-dir build -j --rerun-failed --output-on-failure
